---
- name: Update and restart Docker containers
  hosts: all

  tasks:
    - name: Update Docker packages on Kubernetes hosts
      apt:
        name: docker-ce
        state: latest
      become: yes
      when: ansible_os_family == "Debian" and 'k8' in inventory_hostname

    - name: Update Docker packages on local host
      apt:
        name: docker.io
        state: latest
      become: yes
      when: ansible_os_family == "Debian" and 'k8' not in inventory_hostname

    - name: Get list of all container IDs
      shell: docker ps -aq
      register: container_ids
      changed_when: false

    - name: Restart all Docker containers
      shell: docker restart {{ item }}
      with_items: "{{ container_ids.stdout_lines }}"
      when: container_ids.stdout_lines | length > 0

    - name: Update all APT packages
      become: yes
      apt:
        name: '*'
        state: latest
      when: ansible_os_family == "Debian"

    - name: Append to local file
      delegate_to: localhost
      lineinfile:
        path: "~/updates/updates.txt"
        line: "Last update on {{ inventory_hostname }}: {{ ansible_date_time.iso8601 }}"
