---
- name: Update and restart including docker container
  hosts: localhost

  tasks:
    - name: Get list of all container IDs
      shell: docker ps -aq
      register: container_ids
      changed_when: false

    - name: Restart all Docker containers
      shell: docker restart {{ item }}
      with_items: "{{ container_ids.stdout_lines }}"
      when: container_ids.stdout_lines | length > 0

    - name: Update all APT packages
      become: yes
      apt:
        name: '*'
        state: latest
      when: ansible_os_family == "Debian"

    - name: Update OS
      become: yes
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Cleanup
      become: yes
      command: sudo apt autoremove --purge

    - name: Check if Homebrew is installed
      shell: which brew
      register: brew_check
      changed_when: false

    - name: Update Homebrew
      shell: brew update
      when: brew_check.stdout != ""

    - name: Upgrade Homebrew packages
      shell: brew upgrade
      when: brew_check.stdout != ""

    - name: Append to local file
      delegate_to: localhost
      lineinfile:
        path: "/mnt/QNAP/backuplogs/updates/updates.txt"
        line: "Last dockerhost update on {{ inventory_hostname }}: {{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - name: Reboot
      shell: systemctl reboot -i
      ignore_errors: true
      become: yes
