---
- name: Change DNS settings to Wheeler default
  hosts: windows
  tasks:
  
  - name: Set DNS server addresses
    win_dns_client:
      adapter_names:
        - "Wi-Fi"
      dns_servers:
        - "185.228.168.10"
        - "185.228.168.11"
        - "172.64.36.1"
        - "172.64.36.2"
