---
- name: Download and install Cloudflare Tunnel on Ubuntu
  hosts: cloudflared_hosts
  become: true
  tasks:
    - name: Download cloudflared package
      ansible.builtin.get_url:
        url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        dest: /tmp/cloudflared.deb

    - name: Install cloudflared package
      ansible.builtin.apt:
        deb: /tmp/cloudflared.deb
        state: present

    - name: Find all cloudflared tunnel services
      ansible.builtin.shell: |
        systemctl list-units --type=service --all | grep -o 'cloudflared-[^ ]*\.service' | sort | uniq
      register: cloudflared_services

    - name: Restart each cloudflared tunnel service
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop: "{{ cloudflared_services.stdout_lines }}"
