---
- name: Install Docker-ce Centos
  hosts: all
  become: true

  tasks:
    - name: Check if pre-requisite packages are installed
      yum:
        list: "{{ item }}"
      loop: [python3-pip, curl, yum-utils, device-mapper-persistent-data, lvm2]
      register: package_status
      ignore_errors: true

    - name: Install pre-requisite packages
      yum:
        name: "{{ item }}"
        state: latest
      loop: "{{ package_status.results | rejectattr('stdout', 'search', '^.*installed.*$') | map(attribute='item') | list }}"
      when: item is defined

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      yum:
        name: "{{ item }}"
        state: latest
      loop: [docker-ce, docker-ce-cli, containerd.io]

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Homebrew as ansible user
      become: yes
      become_user: ansible
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /home/ansible/.linuxbrew

    - name: Add Homebrew to ansible user's PATH
      become: yes
      become_user: ansible
      lineinfile:
        path: /home/ansible/.bashrc
        line: 'eval "$(/home/ansible/.linuxbrew/bin/brew shellenv)"'
        create: yes

    - name: Install 'Development Tools'
      become: yes
      yum:
        name: '@Development Tools'
        state: present

    - name: Install gcc with Homebrew
      become: yes
      become_user: ansible
      homebrew:
        name: gcc
        state: present

    - name: Add Homebrew tap for dry
      become: yes
      become_user: ansible
      homebrew_tap:
        name: moncho/dry
        state: present

    - name: Install dry with Homebrew
      become: yes
      become_user: ansible
      homebrew:
        name: dry
        state: present