---
- name: Install Docker-ce Ubuntu
  hosts: all
  become: true

  tasks:

    - name: Gather package facts
      package_facts:
        manager: auto

    - name: Install pre-requisite packages
      apt:
        name: "{{ item }}"
        state: latest
      loop: [python3-pip, curl, apt-transport-https, ca-certificates, software-properties-common]
      when: "item not in ansible_facts.packages"
      ignore_errors: true

    - name: Install 'Development Tools'
      become: yes
      apt:
        name: build-essential
        state: present

    - name: Install gcc with Homebrew
      become: yes
      apt:
        name: gcc
        state: present

    - name: Add Homebrew tap for dry
      become: yes
      become_user: ansible
      shell: /bin/bash -c "sudo snap install dry --edge"

    - name: Add dry to ansible user's PATH
      become: yes
      become_user: ansible
      lineinfile:
        path: /home/ansible/.bashrc
        line: 'export PATH="/snap/bin:$PATH"'
        create: yes

    - name: Add HOMEBREW_NO_ENV_HINTS to .bashrc
      become: yes
      become_user: ansible
      lineinfile:
        path: /home/ansible/.bashrc
        line: 'export HOMEBREW_NO_ENV_HINTS=1'
        create: yes

    - name: Source .bashrc
      become: yes
      become_user: ansible
      shell: source /home/ansible/.bashrc
      args:
        executable: /bin/bash

    - name: Install brew packages
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - fzf
        - git
        - htop
        - mc
        - neofetch
        - nmap
        - tldr
        - zsh
        - zsh-syntax-highlighting
