---
- hosts: k8s_cluster
  serial: 1
  tasks:
    - name: Drain the node
      command: kubectl drain {{ inventory_hostname }} --ignore-daemonsets --delete-emptydir-data
      delegate_to: k8-primary

    - name: Reboot the node
      shell: /sbin/reboot
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for SSH to come back
      wait_for_connection:
        delay: 15
        timeout: 300

    - name: Uncordon the node
      command: kubectl uncordon {{ inventory_hostname }}
      delegate_to: k8-primary
